// solid/src/tasks/CRUD.js
import { createState, createEffect, createMemo } from "solid-js";
import Card from "../components/Card";

import "./CRUD.css";

const CRUD = () => {
  let [state, setState] = createState({
    prefix: "",
    name: "",
    surname: "",
    selected: -1,
    entries: [
      ["Paul", "Atreides"],
      ["Gurney", "Halleck"],
      ["Duncan", "Idaho"]
    ]
  });

  let filteredEntries = createMemo(() =>
    // get filtered entries in which entry[1] startsWith prefix
    // get array of [entry[0], entry[1], index]
    state.entries
      .map((entry, i) => [entry[0], entry[1], i])
      .filter(entry =>
        entry[1].toLowerCase().startsWith(state.prefix.toLowerCase())
      )
  );

  createEffect(() => {
    state.prefix;
    setState({ selected: -1 });
  });

  function createHandler() {
    setState({
      entries: state.entries.concat([[state.name, state.surname]])
    });
  }
  function updateHandler() {
    // if selected > -1 then update entries[selected]
    if (state.selected > -1) {
      setState("entries", [state.selected], [state.name, state.surname]);
    }
  }
  function deleteHandler() {
    // if selected > -1 then delete entries[selected]
    if (state.selected > -1) {
      setState({
        entries: state.entries.filter((entry, i) => i != state.selected)
      });
    }
  }

  return (
    <Card title="CRUD">
      <div class="wrapper">
        Filter prefix:
        <input
          value={state.prefix}
          oninput={e => setState({ prefix: e.target.value })}
        />
        <select
          value={state.selected}
          oninput={e => setState({ selected: e.target.value })}
          size="4"
        >
          {filteredEntries().map(entry => (
            <option value={entry[2]}>
              {entry[1]}, {entry[0]}
            </option>
          ))}
        </select>
        <div>
          Name:
          <input
            value={state.name}
            oninput={e => setState({ name: e.target.value })}
          />
          Surname:
          <input
            value={state.surname}
            oninput={e => setState({ surname: e.target.value })}
          />
        </div>
        <div class="buttons">
          <button onclick={createHandler}>Create</button>
          <button onclick={updateHandler}>Update</button>
          <button onclick={deleteHandler}>Delete</button>
        </div>
      </div>
    </Card>
  );
};

export default CRUD;

// svelte/src/tasks/crud.svelte
<script>
  import Card from "../components/card.svelte";

  let prefix = ''
  let entries = [
    ['Paul', 'Atreides'],
    ['Gurney', 'Halleck'],
    ['Duncan', 'Idaho']
  ]
  $: filteredEntries = entries.filter(
    entry => entry[1].toLowerCase().startsWith(prefix.toLowerCase())
  )
  let selected = 0
  let name = ''
  let surname = ''

  function createHandler() {
    entries.push([name, surname])
    entries = entries
  }
  function updateHandler() {
    entries[selected] = [name, surname]
    entries = entries
  }
  function deleteHandler() {
    entries = entries.filter((entry, i) => i != selected)
  }
</script>

<Card title="CRUD">
  <div class="wrapper">
    Filter prefix: 
    <input bind:value={prefix} />
    <select bind:value={selected} size='4'>
      {#each filteredEntries as entry, i}
        <option value={i}>{entry[1]}, {entry[0]}</option>
      {/each}
    </select>
    <div>
      Name:
      <input bind:value={name} />
      Surname:
      <input bind:value={surname} />
    </div>
    <div class="buttons">
      <button on:click={createHandler}>Create</button>
      <button on:click={updateHandler}>Update</button>
      <button on:click={deleteHandler}>Delete</button>
    </div>
  </div>
</Card>

<style>
  .wrapper {
    max-width: 400px;
    text-align: left;
    margin: auto;
    display: grid;
    grid-template-columns: 150px auto;
    grid-template-rows: auto;
    grid-gap: 10px 10px;
    grid-auto-flow: row;
  }

  .buttons {
    grid-column: 1/3;
    display: flex;
    justify-content: space-evenly;
  }

  button {
    flex: 1 1 0%;
  }

  input {
    width: 100%;
  }
</style>
