// react-vanilla/src/App.js
import React from "react";
import { Counter } from "./tasks/Counter";
import { TemperatureConverter } from "./tasks/TemperatureConverter";
import { FlightBooker } from "./tasks/FlightBooker";
import { Timer } from "./tasks/Timer";
import { CRUD } from "./tasks/CRUD"

import "./App.css";

const App = () => {
  return (
    <main className="App">
      <a href="../../index.html">Home</a>

      <Counter />
      <TemperatureConverter />
      <FlightBooker />
      <Timer />
      <CRUD />
    </main>
  );
};

export default App;

// svelte/src/App.svelte
<script>
	import Counter from './tasks/counter.svelte'
	import TemperatureConverter from './tasks/TemperatureConverter.svelte'
	import FlightBooker from './tasks/flightBooker.svelte'
	import Timer from './tasks/timer.svelte'
	import Crud from './tasks/crud.svelte'
	import CircleDrawer from './tasks/circleDrawer.svelte'
	import Cells from './tasks/cells/cells.svelte'
</script>

<main>
	<a href="../../index.html">Home</a>

	<Counter />
	<TemperatureConverter />
	<FlightBooker />
	<Timer />
	<Crud />
	<CircleDrawer />
	<Cells />
</main>

<style>
	main {
		max-width: 800px;
		margin: auto;
	}
</style>
