// react-vanilla/src/tasks/Timer.js
import React, { useState, useEffect } from "react";
import { Card } from "../components/Card";

import "./Timer.css";

const MAX = 30000;

const formatDuration = (duration) => {
  return (duration / 1000).toFixed(1);
};

const getNow = () => new Date().valueOf();

const Progress = ({ start, duration }) => {
  let [time, setTime] = useState(start);

  useEffect(() => {
    let interval = setInterval(() => {
      setTime(getNow());
    }, 10);
    return () => {
      clearInterval(interval);
    };
  }, []);

  return <progress value={(time - start) / duration} />;
};

export const Timer = () => {
  let [duration, setDuration] = useState(5000);
  let [start, setStart] = useState(getNow());

  function resetTimer() {
    let now = getNow();
    setStart(now);
  }

  return (
    <Card title="Timer">
      <div className="wrapper">
        Elapsed Time: <Progress start={start} duration={duration} />
        <div className="duration">{formatDuration(duration)}</div>
        Duration:
        <input
          type="range"
          min="0"
          max={MAX}
          value={duration}
          onChange={(e) => setDuration(e.target.value)}
        />
        <button onClick={resetTimer}>Reset Timer</button>
      </div>
    </Card>
  );
};

// solid/src/tasks/Timer.js
import {createState, onCleanup, createMemo} from 'solid-js'
import Card from "../components/Card";

import "./Timer.css";

const Timer = () => {
  const MAX = 30000;

  let [state, setState] = createState({
    duration: 5000,
    start: undefined,
    time: undefined,
    interval: undefined
  })

  let durationFormatted = createMemo(() => (state.duration / 1000).toFixed(1))
  let progress = createMemo(() => (state.time - state.start) / state.duration)

  function createInterval() {
    return setInterval(() => {
      setState({
        time: new Date().valueOf()
      })
    }, 10);
  }
  function startTimer() {
    clearInterval(state.interval);
    let date = new Date().valueOf()
    setState({
      start: date,
      time: date,
      interval: createInterval()
    })
  }

  onCleanup(() => clearInterval(state.interval))

  startTimer();

  return (
    <Card title="Timer">
      <div class="wrapper">
        Elapsed Time:
        <progress value={progress() || 0} />
        <div class="duration">{durationFormatted()}s</div>
        Duration:
        <input
          type="range"
          min={0}
          max={MAX}
          value={state.duration}
          oninput={e => setState({duration: e.target.value})}
        />
        <button onclick={startTimer}>Reset Timer</button>
      </div>
    </Card>
  )
};

export default Timer
