// svelte/src/tasks/timer.svelte
<script>
  import Card from "../components/card.svelte";

  const MAX = 30000;

  let duration = 5000;
  let start;

  let time;
  let interval;
  function createInterval() {
    return setInterval(() => {
      time = new Date().valueOf();
    }, 10);
  }
  function startTimer() {
    clearInterval(interval)
    start = new Date().valueOf();
    time = start;
    interval = createInterval();
  }

  startTimer();
</script>

<Card title="Timer">
  <div class="wrapper">
    Elapsed Time:
    <progress value={(time-start)/duration} />
    <div class="duration">{(duration / 1000).toFixed(1)}s</div>
    Duration:
    <input type="range" min={0} max={MAX} bind:value={duration} />
    <button on:click={startTimer}>Reset Timer</button>
  </div>
</Card>

<style>
  .wrapper {
    max-width: 400px;
    text-align: left;
    margin: auto;
    display: grid;
    grid-template-columns: auto auto;
    grid-template-rows: auto;
    grid-gap: 10px 10px;
    grid-auto-flow: row;
  }

  input {
    padding: 0;
    justify-self: stretch;
    align-self: center;
  }

  button {
    grid-column: 1/3;
    grid-row: auto;
  }

  .duration {
    grid-column: 2;
  }
</style>

// solid/src/tasks/Timer.js
import {createState, onCleanup, createMemo} from 'solid-js'
import Card from "../components/Card";

import "./Timer.css";

const Timer = () => {
  const MAX = 30000;

  let [state, setState] = createState({
    duration: 5000,
    start: undefined,
    time: undefined,
    interval: undefined
  })

  let durationFormatted = createMemo(() => (state.duration / 1000).toFixed(1))
  let progress = createMemo(() => (state.time - state.start) / state.duration)

  function createInterval() {
    return setInterval(() => {
      setState({
        time: new Date().valueOf()
      })
    }, 10);
  }
  function startTimer() {
    clearInterval(state.interval);
    let date = new Date().valueOf()
    setState({
      start: date,
      time: date,
      interval: createInterval()
    })
  }

  onCleanup(() => clearInterval(state.interval))

  startTimer();

  return (
    <Card title="Timer">
      <div class="wrapper">
        Elapsed Time:
        <progress value={progress() || 0} />
        <div class="duration">{durationFormatted()}s</div>
        Duration:
        <input
          type="range"
          min={0}
          max={MAX}
          value={state.duration}
          oninput={e => setState({duration: e.target.value})}
        />
        <button onclick={startTimer}>Reset Timer</button>
      </div>
    </Card>
  )
};

export default Timer
