// solid/src/tasks/Counter.js
import { createState } from "solid-js";
import Card from "../components/Card";

import "./Counter.css";

const Counter = () => {
  let [state, setState] = createState({count: 0});

  return (
    <Card title="Counter">
      {state.count}
      <button onclick={() => setState("count", c => c+1)}>+</button>
    </Card>
  )
};

export default Counter

// react-vanilla/src/tasks/Counter.js
import React, { useState } from "react";
import { Card } from "../components/Card";

import "./Counter.css";

export const Counter = () => {
  let [count, setCount] = useState(0);

  function handleClick() {
    setCount(count + 1);
  }

  return (
    <Card title="Counter">
      {count}
      <button onClick={handleClick}>+</button>
    </Card>
  );
};
