// solid/src/tasks/CRUD.js
import { createState, createEffect, createMemo } from "solid-js";
import Card from "../components/Card";

import "./CRUD.css";

const CRUD = () => {
  let [state, setState] = createState({
    prefix: "",
    name: "",
    surname: "",
    selected: -1,
    entries: [
      ["Paul", "Atreides"],
      ["Gurney", "Halleck"],
      ["Duncan", "Idaho"]
    ]
  });

  let filteredEntries = createMemo(() =>
    // get filtered entries in which entry[1] startsWith prefix
    // get array of [entry[0], entry[1], index]
    state.entries
      .map((entry, i) => [entry[0], entry[1], i])
      .filter(entry =>
        entry[1].toLowerCase().startsWith(state.prefix.toLowerCase())
      )
  );

  createEffect(() => {
    state.prefix;
    setState({ selected: -1 });
  });

  function createHandler() {
    setState({
      entries: state.entries.concat([[state.name, state.surname]])
    });
  }
  function updateHandler() {
    // if selected > -1 then update entries[selected]
    if (state.selected > -1) {
      setState("entries", [state.selected], [state.name, state.surname]);
    }
  }
  function deleteHandler() {
    // if selected > -1 then delete entries[selected]
    if (state.selected > -1) {
      setState({
        entries: state.entries.filter((entry, i) => i != state.selected)
      });
    }
  }

  return (
    <Card title="CRUD">
      <div class="wrapper">
        Filter prefix:
        <input
          value={state.prefix}
          oninput={e => setState({ prefix: e.target.value })}
        />
        <select
          value={state.selected}
          oninput={e => setState({ selected: e.target.value })}
          size="4"
        >
          {filteredEntries().map(entry => (
            <option value={entry[2]}>
              {entry[1]}, {entry[0]}
            </option>
          ))}
        </select>
        <div>
          Name:
          <input
            value={state.name}
            oninput={e => setState({ name: e.target.value })}
          />
          Surname:
          <input
            value={state.surname}
            oninput={e => setState({ surname: e.target.value })}
          />
        </div>
        <div class="buttons">
          <button onclick={createHandler}>Create</button>
          <button onclick={updateHandler}>Update</button>
          <button onclick={deleteHandler}>Delete</button>
        </div>
      </div>
    </Card>
  );
};

export default CRUD;

// react-vanilla/src/tasks/CRUD.js
import React, { useState, useEffect } from "react";
import { Card } from "../components/Card";

import "./CRUD.css";

let initialState = [
  ["Paul", "Atreides"],
  ["Gurney", "Halleck"],
  ["Duncan", "Idaho"],
];

let Entries = ({ prefix, entries, selected, setSelected }) => {
  let filteredEntries = entries
    .map((entry, i) => [entry[0], entry[1], i])
    .filter((entry) => entry[1].toLowerCase().startsWith(prefix.toLowerCase()));

  return (
    <select
      value={selected}
      onChange={(e) => setSelected(e.target.value)}
      size="4"
    >
      {filteredEntries.map((entry, i) => (
        <option value={i} key={i + entry[0] + entry[1]}>
          {entry[1]}, {entry[0]}
        </option>
      ))}
    </select>
  );
};

let NamesAndButtons = ({ create, update, del }) => {
  let [name, setName] = useState("");
  let [surname, setSurname] = useState("");

  return (
    <>
      <div>
        Name:
        <input value={name} onChange={(e) => setName(e.target.value)} />
        Surname:
        <input value={surname} onChange={(e) => setSurname(e.target.value)} />
      </div>
      <div className="buttons">
        <button onClick={() => create(name, surname)}>Create</button>
        <button onClick={() => update(name, surname)}>Update</button>
        <button onClick={del}>Delete</button>
      </div>
    </>
  );
};

export const CRUD = () => {
  let [prefix, setPrefix] = useState("");
  let [entries, setEntries] = useState(initialState);
  let [selected, setSelected] = useState(-1);

  function create(name, surname) {
    let newEntries = entries.slice();
    newEntries.push([name, surname]);
    setEntries(newEntries);
  }
  function update(name, surname) {
    if (selected > -1) {
      let newEntries = entries.slice();
      newEntries[selected] = [name, surname];
      setEntries(newEntries);
    }
  }
  function del() {
    if (selected > -1) setEntries(entries.filter((v, i) => i != selected));
  }

  return (
    <Card title="CRUD">
      <div className="wrapper">
        Filter prefix:
        <input
          value={prefix}
          onChange={(e) => {
            setPrefix(e.target.value);
            setSelected(-1);
          }}
        />
        <Entries
          entries={entries}
          prefix={prefix}
          selected={selected}
          setSelected={setSelected}
        />
        <NamesAndButtons create={create} update={update} del={del} />
      </div>
    </Card>
  );
};
