// solid/src/tasks/FlightBooker.js
import { createState, createMemo } from "solid-js";
import Card from "../components/Card";
import "./FlightBooker.css";

let flightMap = {
  1: "one-way flight",
  2: "return flight"
};

function tryAsDate(dateString) {
  let dateArr = dateString.split(".").reverse();
  if (dateArr[1].length !== 2 || dateArr[2].length !== 2) {
    return false;
  }
  let date = new Date(dateArr.join("-"));
  return date.valueOf() || false;
}

function formatAsString(date) {
  return date
    .toISOString()
    .slice(0, 10)
    .split("-")
    .reverse()
    .join(".");
}

const FlightBooker = () => {
  let [state, setState] = createState({
    flightType: 1,
    startDate: formatAsString(new Date()),
    returnDate: formatAsString(new Date())
  });

  let error1 = createMemo(() => !tryAsDate(state.startDate));
  let error2 = createMemo(() => !tryAsDate(state.returnDate));
  let error3 = createMemo(
    () => tryAsDate(state.returnDate) < tryAsDate(state.startDate)
  );

  let isBookButtonDisabled = createMemo(() => error1() || error2() || error3());
  let isOneWay = createMemo(() => state.flightType === 1);
  let startDateClass = createMemo(() => (error1() ? "error" : ""));
  let returnDateClass = createMemo(() => (error2() ? "error" : ""));

  function book() {
    let timeStrings = {
      1: " for " + state.startDate,
      2: " from " + state.startDate + " to " + state.returnDate
    };
    alert(
      "You have booked a " +
        flightMap[state.flightType] +
        timeStrings[state.flightType]
    );
  }

  return (
    <Card title="Flight Booker">
      <div>
        <select
          value={state.flightType}
          onchange={e => setState({ flightType: Number(e.target.value) })}
        >
          <option value={1}>{flightMap[1]}</option>
          <option value={2}>{flightMap[2]}</option>
        </select>
        <input
          value={state.startDate}
          class={startDateClass()}
          oninput={e => setState({ startDate: e.target.value })}
        />
        <input
          value={state.returnDate}
          class={returnDateClass()}
          oninput={e => setState({ returnDate: e.target.value })}
          disabled={isOneWay()}
        />
        <button onclick={book} disabled={isBookButtonDisabled()}>
          Book
        </button>
      </div>
    </Card>
  );
};

export default FlightBooker;

// react-vanilla/src/tasks/FlightBooker.js
import React, { useState, useEffect } from "react";
import { Card } from "../components/Card";

import "./FlightBooker.css";

let flightTypes = ["one-way flight", "return flight"];

function tryAsDate(dateString) {
  try {
    let dateArr = dateString.split(".").reverse();
    if (dateArr[1].length !== 2 || dateArr[2].length !== 2) {
      return false;
    }
    let date = new Date(dateArr.join("-"));
    return date.getTime() || false;
  } catch (e) {
    return false;
  }
}

function formatAsString(date) {
  return date.toISOString().slice(0, 10).split("-").reverse().join(".");
}

export const FlightBooker = () => {
  const [flightType, setFlightType] = useState(0);
  const [startDate, setStartDate] = useState(formatAsString(new Date()));
  const [returnDate, setReturnDate] = useState(formatAsString(new Date()));

  let isOneWay = !flightType;

  // Errors
  let e1 = !tryAsDate(startDate);
  let e2 = !tryAsDate(returnDate);
  let e3 = !isOneWay && tryAsDate(returnDate) < tryAsDate(startDate);

  function book() {
    let timeStrings = [
      " for " + startDate,
      " from " + startDate + " to " + returnDate,
    ];
    alert(
      "You have booked a " + flightTypes[flightType] + timeStrings[flightType]
    );
  }

  return (
    <Card title="Flight Booker">
      <div>
        <select
          value={flightType}
          onChange={(e) => setFlightType(e.target.value)}
        >
          <option value={0}>{flightTypes[0]}</option>
          <option value={1}>{flightTypes[1]}</option>
        </select>
        <input
          value={startDate}
          className={e1 ? "error" : ""}
          onChange={(e) => setStartDate(e.target.value)}
          placeholder="dd.mm.yyyy"
        />
        <input
          value={returnDate}
          className={e2 ? "error" : ""}
          onChange={(e) => setReturnDate(e.target.value)}
          placeholder="dd.mm.yyyy"
          disabled={isOneWay}
        />
        <button onClick={book} disabled={e1 || e2 || e3} type="button">
          Book
        </button>
      </div>
    </Card>
  );
};
