// svelte/src/tasks/tempConverter.svelte
<script>
  import Card from '../components/card.svelte'

  let c = 0
  let f

  function trunc(n) {
    return Number(n.toFixed(2))
  }
  function updateC() {
    f = Number(f) || 0
    c = trunc((5/9) * (f - 32))
  }
  function updateF() {
    c = Number(c) || 0 
    f = trunc(((9/5) * c) + 32)
  }

  updateF()
</script>

<Card title="Temperature Converter">
  <span><input bind:value={c} on:input={updateF}/> Celsius</span>
  &nbsp;&nbsp;=&nbsp;&nbsp;
  <span><input bind:value={f} on:input={updateC}/> Fahrenheit</span>
</Card>

<style>
  span {
    display: inline-block;
  }
</style>

// react-vanilla/src/tasks/TempConverter.js
import React, { useState} from "react";
import { Card } from "../components/Card";

import './TempConverter.css'

function trunc(n) {
  return Number(n.toFixed(2));
}
function getC(f) {
  return trunc((5 / 9) * (f - 32));
}
function getF(c) {
  return trunc((9 / 5) * c + 32);
}
let r = /^\d+.?\d*$/

export const TempConverter = () => {
  let [c, setC] = useState(0);
  let [f, setF] = useState(32);

  function updateFromC(e) {
    let { value } = e.target;
    if (r.test(value)) {
      value = Number(value)
      setC(value);
      setF(getF(value));
    }
  }

  function updateFromF(e) {
    let { value } = e.target
    if (r.test(value)) {
      value = Number(value);
      setF(value);
      setC(getC(value));
    }
  }

  return (
    <Card title="Temperature Converter">
      <span>
        <input value={c} onChange={updateFromC} /> Celsius
      </span>
      =
      <span>
        <input value={f} onChange={updateFromF} /> Fahrenheit
      </span>
    </Card>
  );
};
